config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :products
  devise_for :users
  root 'home#index'
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"

  get '*path', to: redirect('/products'), constraints: lambda { |req|
      req.path.exclude? 'rails/active_storage'
    }


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get '/user' => "products#index", :as => :user_root

end

app/views/shared/_navbar.html.erb
<nav>
        <%# <div id="logo"> %>
            <% if user_signed_in? %>
                <%= link_to image_tag("Finsz-logo-orange-on-white-500px.png", :class => "logo"), products_path %>
            <% else %>
                <%= link_to image_tag("Finsz-logo-orange-on-white-500px.png", :class => "logo"), root_path %>
            <% end %>
        <%# </div> %>
        <div id="account_options">
            <% if user_signed_in? %>
                <div id="user_signout">
                    <li><%= link_to "Sign Out", destroy_user_session_path, method: "delete" %></li>
                </div>
                <div id="user_edit">
                    <li><%= link_to "My Account", edit_user_registration_path, method: "get" %></li>
                </div>
                <div id="user_orders">
                    <li><%= link_to "My Purchases", orders_path, method: "get" %></li>
                </div>
            <% else %>
                <div id="user_signin">
                    <li><%= link_to "Sign In", new_user_session_path %></li>
                </div>
                <div id="create_acc">
                    <li><%= link_to "Create Account", new_user_registration_path %></li>
                </div>
            <% end %>
        </div>
</nav>