config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :products
  devise_for :users
  root 'home#index'
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"

  get '*path', to: redirect('/products'), constraints: lambda { |req|
      req.path.exclude? 'rails/active_storage'
    }


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get '/user' => "products#index", :as => :user_root

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :seller, class_name: 'User'
  belongs_to :buyer, class_name: 'User'
  belongs_to :product
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = current_user.purchases
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:seller_id, :buyer_id, :product_id, :product_name, :product_price)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :seller_id_id %>
    <%= form.text_field :seller_id_id %>
  </div>

  <div class="field">
    <%= form.label :buyer_id_id %>
    <%= form.text_field :buyer_id_id %>
  </div>

  <div class="field">
    <%= form.label :product_id_id %>
    <%= form.text_field :product_id_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Purchases</h1>

<table>
  <thead>
    <tr>
      <th>Order No.</th>
      <th>Seller</th>
      <th>Buyer</th>
      <th>Product. ID</th>
      <th>Product</th>
      <th>Price</th>
      <th>Purchase Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.seller.display_name %></td>
        <%# Skip one layer of lookup by accessing via session. %>
        <td><%= current_user.display_name %></td>
        <td><%= order.product_id %></td>
        <td><%= order.product_name %></td>
        <td><%= order.product_price %></td>
        <td><%= order.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Seller:</strong>
  <%= @order.seller_id_id %>
</p>

<p>
  <strong>Buyer:</strong>
  <%= @order.buyer_id_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @order.product_id_id %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>